name: Varscan
description: Detect variants and indels in NGS data from mpileup file
authors:
  - Thibault Dayris
input:
  - A mpileup file
output:
  - A VCF file
notes: |
  Varscan does not take any threading information by itself. However, mpileup
  files given as input, might be gzipped.

  If so, it's recommended to use two threads:

  * 1 for varscan itself
  * 1 for zcat
