name: varscan somatic
description: Varscan Somatic calls variants and identifies their somatic status (Germline/LOH/Somatic) using pileup files from a matched tumor-normal pair.
authors:
  - Thibault Dayris
input:
  - A pair of pileup files (Normal/Tumor)
output:
  - A VCF file
