channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >=3.6
  - bowtie2 == 2.3.4.3
  - bismark == 0.22.1
  - samtools == 1.9
  - perl-gdgraph == 1.54  # for bismark plots module
