name: varscan mpileup2indel
description: Detect indel in NGS data from mpileup files
authors:
  - Thibault Dayris
input:
  - A mpileup file
output:
  - A VCF file
notes: |
  Varscan does not take any threading information by itself. However, mpileup
  files given as input, might be gzipped.

  If so, it's recommended to use two threads:

  * 1 for varscan itself
  * 1 for zcat
